import type { Language } from './types';

export const translations: { [key: string]: { [key: string]: string } } = {
  en: { goal_title: "What is your goal?", goal_subtitle: "Select one for a recommendation.", start_btn: "Start", mixer_title: "Adjust Volume", main_volume: "Main Volume", background_volume: "Background Volume", turn_off_all: "Turn Off All Background Sounds", language_title: "Select Language", sleep_timer_title: "Sleep Timer", sleep_timer_remaining: "Time Remaining", sleep_timer_15m: "15 Minutes", sleep_timer_30m: "30 Minutes", sleep_timer_60m: "60 Minutes", sleep_timer_custom: "Custom", sleep_timer_set: "Set Timer", sleep_timer_cancel: "Cancel Timer", start_listening_btn: "Start Listening", continue_without_timer: "Continue without timer", select_sleep_timer_title: "Set a Sleep Timer", select_sleep_timer_subtitle: "Automatically stop playback after a set time.", mixer_onboarding_title: "Mix Background Sounds", mixer_onboarding_subtitle: "Enhance your experience. (Optional)", feedback_title: "How was your session?", feedback_yes: "I loved it!", feedback_no: "Not for me", feedback_thanks_title: "That's great!", feedback_share_prompt: "Help others find their calm. Share this app with your friends.", feedback_share_button: "Share", share_message_title: "Relaxing Melody Player", share_message_text: "I'm using this app to relax and focus. You might like it too!", feedback_close_button: "Close", album_solfeggio: "Solfeggio Frequencies", album_binaural: "Binaural Beats", install_app: "Install App", feedback_playback_started: "Playback started", feedback_playback_paused: "Playback paused", feedback_next_track: "Next track", feedback_prev_track: "Previous track", feedback_sound_enabled: "enabled", feedback_sound_disabled: "disabled", feedback_timer_set: "Sleep timer set for", feedback_minutes: "minutes", feedback_timer_finished: "Sleep timer finished. Playback stopped" },
  vi: { goal_title: "Mục tiêu của bạn?", goal_subtitle: "Chọn một để nhận gợi ý.", start_btn: "Bắt đầu", mixer_title: "Điều Chỉnh Âm Lượng", main_volume: "Âm lượng chính", background_volume: "Âm lượng nền", turn_off_all: "Tắt tất cả âm nền", language_title: "Chọn Ngôn Ngữ", sleep_timer_title: "Hẹn giờ ngủ", sleep_timer_remaining: "Thời gian còn lại", sleep_timer_15m: "15 phút", sleep_timer_30m: "30 phút", sleep_timer_60m: "60 phút", sleep_timer_custom: "Tùy chỉnh", sleep_timer_set: "Đặt hẹn giờ", sleep_timer_cancel: "Hủy hẹn giờ", start_listening_btn: "Bắt đầu nghe", continue_without_timer: "Tiếp tục không hẹn giờ", select_sleep_timer_title: "Hẹn giờ ngủ", select_sleep_timer_subtitle: "Tự động dừng phát sau một khoảng thời gian.", mixer_onboarding_title: "Phối Âm Nền", mixer_onboarding_subtitle: "Thêm âm thanh để tăng trải nghiệm. (Tùy chọn)", feedback_title: "Buổi nghe của bạn thế nào?", feedback_yes: "Tôi rất thích!", feedback_no: "Không hợp với tôi", feedback_thanks_title: "Tuyệt vời!", feedback_share_prompt: "Giúp người khác tìm thấy sự bình yên. Hãy chia sẻ ứng dụng này với bạn bè.", feedback_share_button: "Chia sẻ", share_message_title: "Ứng dụng Giai điệu Thư giãn", share_message_text: "Mình đang dùng ứng dụng này để thư giãn và tập trung. Bạn cũng thử xem!", feedback_close_button: "Đóng", album_solfeggio: "Tần số Solfeggio", album_binaural: "Sóng Âm Não", install_app: "Cài đặt", feedback_playback_started: "Đã bắt đầu phát", feedback_playback_paused: "Đã tạm dừng phát", feedback_next_track: "Bài tiếp theo", feedback_prev_track: "Bài trước đó", feedback_sound_enabled: "đã bật", feedback_sound_disabled: "đã tắt", feedback_timer_set: "Đã đặt hẹn giờ ngủ trong", feedback_minutes: "phút", feedback_timer_finished: "Hẹn giờ ngủ đã kết thúc. Đã dừng phát" },
  zh: { goal_title: "您的目标是什么？", goal_subtitle: "选择一个以获得推荐。", start_btn: "开始", mixer_title: "调整音量", main_volume: "主音量", background_volume: "背景音量", turn_off_all: "关闭所有背景音", language_title: "选择语言", sleep_timer_title: "睡眠定时器", sleep_timer_remaining: "剩余时间", sleep_timer_15m: "15分钟", sleep_timer_30m: "30分钟", sleep_timer_60m: "60分钟", sleep_timer_custom: "自定义", sleep_timer_set: "设置计时器", sleep_timer_cancel: "取消计时器", start_listening_btn: "开始聆听", continue_without_timer: "无计时器继续", select_sleep_timer_title: "设置睡眠定时器", select_sleep_timer_subtitle: "在设定时间后自动停止播放。", mixer_onboarding_title: "混合背景音", mixer_onboarding_subtitle: "增强您的体验。（可选）", feedback_title: "您的体验如何？", feedback_yes: "我喜欢！", feedback_no: "不适合我", feedback_thanks_title: "太好了！", feedback_share_prompt: "帮助他人找到平静。与您的朋友分享此应用。", feedback_share_button: "分享", share_message_title: "轻松旋律播放器", share_message_text: "我正在使用此应用放松和专注。您可能也会喜欢！", feedback_close_button: "关闭", album_solfeggio: "视唱练耳频率", album_binaural: "双耳节拍", install_app: "安装应用", feedback_playback_started: "播放已开始", feedback_playback_paused: "播放已暂停", feedback_next_track: "下一首", feedback_prev_track: "上一首", feedback_sound_enabled: "已启用", feedback_sound_disabled: "已禁用", feedback_timer_set: "睡眠定时器设置为", feedback_minutes: "分钟", feedback_timer_finished: "睡眠定时器已结束。播放已停止" },
  ja: { goal_title: "あなたの目標は？", goal_subtitle: "一つ選択して推薦を得る。", start_btn: "開始", mixer_title: "音量調整", main_volume: "主音量", background_volume: "背景音量", turn_off_all: "すべての背景音をオフ", language_title: "言語を選択", sleep_timer_title: "スリープタイマー", sleep_timer_remaining: "残り時間", sleep_timer_15m: "15分", sleep_timer_30m: "30分", sleep_timer_60m: "60分", sleep_timer_custom: "カスタム", sleep_timer_set: "タイマーを設定", sleep_timer_cancel: "タイマーをキャンセル", start_listening_btn: "リスニング開始", continue_without_timer: "タイマーなしで続行", select_sleep_timer_title: "スリープタイマーを設定", select_sleep_timer_subtitle: "設定時間後に再生を自動的に停止します。", mixer_onboarding_title: "背景音をミックス", mixer_onboarding_subtitle: "あなたの体験を向上させます。（オプション）", feedback_title: "セッションはいかがでしたか？", feedback_yes: "大好き！", feedback_no: "私には合わない", feedback_thanks_title: "素晴らしい！", feedback_share_prompt: "他の人が落ち着きを見つけるのを手伝ってください。このアプリを友達と共有してください。", feedback_share_button: "共有", share_message_title: "リラックスメロディープレーヤー", share_message_text: "私はこのアプリを使ってリラックスし、集中しています。あなたも好きかもしれません！", feedback_close_button: "閉じる", album_solfeggio: "ソルフェジオ周波数", album_binaural: "バイノーラルビート", install_app: "インストール", feedback_playback_started: "再生を開始しました", feedback_playback_paused: "再生を一時停止しました", feedback_next_track: "次のトラック", feedback_prev_track: "前のトラック", feedback_sound_enabled: "有効", feedback_sound_disabled: "無効", feedback_timer_set: "スリープタイマーを", feedback_minutes: "分に設定", feedback_timer_finished: "スリープタイマーが終了しました。再生を停止しました" },
  ko: { goal_title: "당신의 목표는?", goal_subtitle: "추천을 받으려면 하나를 선택。", start_btn: "시작", mixer_title: "볼륨 조절", main_volume: "메인 볼륨", background_volume: "배경 볼륨", turn_off_all: "모든 배경 사운드 끄기", language_title: "언어 선택", sleep_timer_title: "수면 타이머", sleep_timer_remaining: "남은 시간", sleep_timer_15m: "15분", sleep_timer_30m: "30분", sleep_timer_60m: "60분", sleep_timer_custom: "사용자 정의", sleep_timer_set: "타이머 설정", sleep_timer_cancel: "타이머 취소", start_listening_btn: "듣기 시작", continue_without_timer: "타이머 없이 계속", select_sleep_timer_title: "수면 타이머 설정", select_sleep_timer_subtitle: "설정된 시간 후에 자동으로 재생을 중지합니다。", mixer_onboarding_title: "배경 사운드 믹싱", mixer_onboarding_subtitle: "경험을 향상시키십시오. (선택 사항)", feedback_title: "세션은 어땠나요?", feedback_yes: "정말 좋았어요!", feedback_no: "저에게는 맞지 않아요", feedback_thanks_title: "멋져요!", feedback_share_prompt: "다른 사람들이 평온을 찾도록 도와주세요. 이 앱을 친구들과 공유하세요.", feedback_share_button: "공유", share_message_title: "편안한 멜로디 플레이어", share_message_text: "저는 이 앱을 사용하여 긴장을 풀고 집중하고 있습니다. 당신도 좋아할 수 있습니다!", feedback_close_button: "닫기", album_solfeggio: "솔페지오 주파수", album_binaural: "바이노럴 비트", install_app: "앱 설치", feedback_playback_started: "재생 시작됨", feedback_playback_paused: "재생 일시 중지됨", feedback_next_track: "다음 트랙", feedback_prev_track: "이전 트랙", feedback_sound_enabled: "활성화됨", feedback_sound_disabled: "비활성화됨", feedback_timer_set: "취침 타이머 설정", feedback_minutes: "분", feedback_timer_finished: "취침 타이머가 종료되었습니다. 재생이 중지되었습니다" },
  fr: { goal_title: "Quel est votre but?", goal_subtitle: "Sélectionnez-en un pour une suggestion.", start_btn: "Commencer", mixer_title: "Ajuster le volume", main_volume: "Volume principal", background_volume: "Volume de fond", turn_off_all: "Désactiver tous les sons de fond", language_title: "Choisir la langue", sleep_timer_title: "Minuterie de sommeil", sleep_timer_remaining: "Temps restant", sleep_timer_15m: "15 Minutes", sleep_timer_30m: "30 Minutes", sleep_timer_60m: "60 Minutes", sleep_timer_custom: "Personnalisé", sleep_timer_set: "Régler la minuterie", sleep_timer_cancel: "Annuler la minuterie", start_listening_btn: "Commencer à écouter", continue_without_timer: "Continuer sans minuterie", select_sleep_timer_title: "Définir une minuterie de sommeil", select_sleep_timer_subtitle: "Arrête automatiquement la lecture après une durée définie.", mixer_onboarding_title: "Mixer les sons de fond", mixer_onboarding_subtitle: "Améliorez votre expérience. (Optionnel)", feedback_title: "Comment était votre session ?", feedback_yes: "J'ai adoré !", feedback_no: "Pas pour moi", feedback_thanks_title: "C'est génial !", feedback_share_prompt: "Aidez les autres à trouver leur calme. Partagez cette application avec vos amis.", feedback_share_button: "Partager", share_message_title: "Lecteur de mélodies relaxantes", share_message_text: "J'utilise cette application pour me détendre et me concentrer. Vous pourriez l'aimer aussi !", feedback_close_button: "Fermer", album_solfeggio: "Fréquences Solfeggio", album_binaural: "Battements Binauraux", install_app: "Installer", feedback_playback_started: "Lecture démarrée", feedback_playback_paused: "Lecture en pause", feedback_next_track: "Piste suivante", feedback_prev_track: "Piste précédente", feedback_sound_enabled: "activé", feedback_sound_disabled: "désactivé", feedback_timer_set: "Minuterie de sommeil réglée sur", feedback_minutes: "minutes", feedback_timer_finished: "Minuterie de sommeil terminée. Lecture arrêtée" },
  de: { goal_title: "Was ist dein Ziel?", goal_subtitle: "Wähle eines für eine Empfehlung.", start_btn: "Start", mixer_title: "Lautstärke anpassen", main_volume: "Hauptlautstärke", background_volume: "Hintergrundlautstärke", turn_off_all: "Alle Hintergrundgeräusche ausschalten", language_title: "Sprache auswählen", sleep_timer_title: "Schlaf-Timer", sleep_timer_remaining: "Verbleibende Zeit", sleep_timer_15m: "15 Minuten", sleep_timer_30m: "30 Minuten", sleep_timer_60m: "60 Minuten", sleep_timer_custom: "Benutzerdefiniert", sleep_timer_set: "Timer einstellen", sleep_timer_cancel: "Timer abbrechen", start_listening_btn: "Zuhören beginnen", continue_without_timer: "Ohne Timer fortfahren", select_sleep_timer_title: "Schlaf-Timer einstellen", select_sleep_timer_subtitle: "Stoppt die Wiedergabe automatisch nach einer festgelegten Zeit.", mixer_onboarding_title: "Hintergrundgeräusche mischen", mixer_onboarding_subtitle: "Verbessern Sie Ihr Erlebnis. (Optional)", feedback_title: "Wie war Ihre Sitzung?", feedback_yes: "Ich fand es toll!", feedback_no: "Nichts für mich", feedback_thanks_title: "Das ist großartig!", feedback_share_prompt: "Helfen Sie anderen, ihre Ruhe zu finden. Teilen Sie diese App mit Ihren Freunden.", feedback_share_button: "Teilen", share_message_title: "Entspannender Melodie-Player", share_message_text: "Ich benutze diese App, um mich zu entspannen und zu konzentrieren. Sie könnte Ihnen auch gefallen!", feedback_close_button: "Schließen", album_solfeggio: "Solfeggio-Frequenzen", album_binaural: "Binaurale Beats", install_app: "Installieren", feedback_playback_started: "Wiedergabe gestartet", feedback_playback_paused: "Wiedergabe pausiert", feedback_next_track: "Nächster Titel", feedback_prev_track: "Vorheriger Titel", feedback_sound_enabled: "aktiviert", feedback_sound_disabled: "deaktiviert", feedback_timer_set: "Sleep-Timer eingestellt auf", feedback_minutes: "Minuten", feedback_timer_finished: "Sleep-Timer beendet. Wiedergabe gestoppt" },
  es: { goal_title: "¿Cuál es tu objetivo?", goal_subtitle: "Selecciona uno para una recomendación.", start_btn: "Empezar", mixer_title: "Ajustar volumen", main_volume: "Volumen principal", background_volume: "Volumen de fondo", turn_off_all: "Apagar todos los sonidos de fondo", language_title: "Seleccionar idioma", sleep_timer_title: "Temporizador de sueño", sleep_timer_remaining: "Tiempo restante", sleep_timer_15m: "15 Minutos", sleep_timer_30m: "30 Minutos", sleep_timer_60m: "60 Minutos", sleep_timer_custom: "Personalizado", sleep_timer_set: "Establecer temporizador", sleep_timer_cancel: "Cancelar temporizador", start_listening_btn: "Comenzar a escuchar", continue_without_timer: "Continuar sin temporizador", select_sleep_timer_title: "Establecer temporizador de sueño", select_sleep_timer_subtitle: "Detiene la reproducción automáticamente después de un tiempo establecido.", mixer_onboarding_title: "Mezclar sonidos de fondo", mixer_onboarding_subtitle: "Mejore su experiencia. (Opcional)", feedback_title: "¿Cómo fue tu sesión?", feedback_yes: "¡Me encantó!", feedback_no: "No es para mí", feedback_thanks_title: "¡Eso es genial!", feedback_share_prompt: "Ayuda a otros a encontrar la calma. Comparte esta aplicación con tus amigos.", feedback_share_button: "Compartir", share_message_title: "Reproductor de melodías relajantes", share_message_text: "Estoy usando esta aplicación para relajarme y concentrarme. ¡Quizás a ti también te guste!", feedback_close_button: "Cerrar", album_solfeggio: "Frecuencias de Solfeo", album_binaural: "Sonidos Binaurales", install_app: "Instalar", feedback_playback_started: "Reproducción iniciada", feedback_playback_paused: "Reproducción pausada", feedback_next_track: "Siguiente pista", feedback_prev_track: "Pista anterior", feedback_sound_enabled: "activado", feedback_sound_disabled: "desactivado", feedback_timer_set: "Temporizador de sueño configurado para", feedback_minutes: "minutos", feedback_timer_finished: "Temporizador de sueño finalizado. Reproducción detenida" },
};

export const languages: Language[] = [
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' }, { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' }, { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' }, { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' }, { code: 'es', name: 'Español', flag: '🇪🇸' },
];

export const goalTranslations = {
  en: { healing_pain: "Healing Pain", focus: "Focus", relax: "Relax", sleep: "Sleep", meditate: "Meditate", tinnitus: "Tinnitus" },
  vi: { healing_pain: "Chữa lành nỗi đau", focus: "Tập trung", relax: "Thư giãn", sleep: "Ngủ", meditate: "Thiền", tinnitus: "Ù tai" },
  zh: { healing_pain: "治愈痛苦", focus: "专注", relax: "放松", sleep: "睡觉", meditate: "冥想", tinnitus: "耳鸣" },
  ja: { healing_pain: "痛みの癒し", focus: "集中", relax: "リラックス", sleep: "睡眠", meditate: "瞑想", tinnitus: "耳鳴り" },
  ko: { healing_pain: "고통 치유", focus: "집중", relax: "휴식", sleep: "수면", meditate: "명상", tinnitus: "이명" },
  fr: { healing_pain: "Guérir la douleur", focus: "Concentration", relax: "Détente", sleep: "Sommeil", meditate: "Méditation", tinnitus: "Acouphènes" },
  de: { healing_pain: "Schmerzheilung", focus: "Fokus", relax: "Entspannen", sleep: "Schlaf", meditate: "Meditieren", tinnitus: "Tinnitus" },
  es: { healing_pain: "Sanar el dolor", focus: "Concentración", relax: "Relajarse", sleep: "Dormir", meditate: "Meditar", tinnitus: "Tinnitus" },
};
