import { SolfeggioFrequency, BinauralBeat, NaturalSound, Language, GoalsData } from './types';

export const translations: { [key: string]: { [key: string]: string } } = {
  en: { goal_title: "What is your goal?", goal_subtitle: "Select one for a recommendation.", start_btn: "Start", mixer_title: "Adjust Volume", main_volume: "Main Volume", background_volume: "Background Volume", turn_off_all: "Turn Off All Background Sounds", language_title: "Select Language", sleep_timer_title: "Sleep Timer", sleep_timer_remaining: "Time Remaining", sleep_timer_15m: "15 Minutes", sleep_timer_30m: "30 Minutes", sleep_timer_60m: "60 Minutes", sleep_timer_custom: "Custom", sleep_timer_set: "Set Timer", sleep_timer_cancel: "Cancel Timer", start_listening_btn: "Start Listening", continue_without_timer: "Continue without timer", select_sleep_timer_title: "Set a Sleep Timer", select_sleep_timer_subtitle: "Automatically stop playback after a set time.", mixer_onboarding_title: "Mix Background Sounds", mixer_onboarding_subtitle: "Enhance your experience. (Optional)", feedback_title: "How was your session?", feedback_yes: "I loved it!", feedback_no: "Not for me", feedback_thanks_title: "That's great!", feedback_share_prompt: "Help others find their calm. Share this app with your friends.", feedback_share_button: "Share", share_message_title: "Relaxing Melody Player", share_message_text: "I'm using this app to relax and focus. You might like it too!", feedback_close_button: "Close", album_solfeggio: "Solfeggio Frequencies", album_binaural: "Binaural Beats", install_app: "Install App" },
  vi: { goal_title: "Mục tiêu của bạn?", goal_subtitle: "Chọn một để nhận gợi ý.", start_btn: "Bắt đầu", mixer_title: "Điều Chỉnh Âm Lượng", main_volume: "Âm lượng chính", background_volume: "Âm lượng nền", turn_off_all: "Tắt tất cả âm nền", language_title: "Chọn Ngôn Ngữ", sleep_timer_title: "Hẹn giờ ngủ", sleep_timer_remaining: "Thời gian còn lại", sleep_timer_15m: "15 phút", sleep_timer_30m: "30 phút", sleep_timer_60m: "60 phút", sleep_timer_custom: "Tùy chỉnh", sleep_timer_set: "Đặt hẹn giờ", sleep_timer_cancel: "Hủy hẹn giờ", start_listening_btn: "Bắt đầu nghe", continue_without_timer: "Tiếp tục không hẹn giờ", select_sleep_timer_title: "Hẹn giờ ngủ", select_sleep_timer_subtitle: "Tự động dừng phát sau một khoảng thời gian.", mixer_onboarding_title: "Phối Âm Nền", mixer_onboarding_subtitle: "Thêm âm thanh để tăng trải nghiệm. (Tùy chọn)", feedback_title: "Buổi nghe của bạn thế nào?", feedback_yes: "Tôi rất thích!", feedback_no: "Không hợp với tôi", feedback_thanks_title: "Tuyệt vời!", feedback_share_prompt: "Giúp người khác tìm thấy sự bình yên. Hãy chia sẻ ứng dụng này với bạn bè.", feedback_share_button: "Chia sẻ", share_message_title: "Ứng dụng Giai điệu Thư giãn", share_message_text: "Mình đang dùng ứng dụng này để thư giãn và tập trung. Bạn cũng thử xem!", feedback_close_button: "Đóng", album_solfeggio: "Tần số Solfeggio", album_binaural: "Sóng Âm Não", install_app: "Cài đặt" },
  zh: { goal_title: "您的目标是什么？", goal_subtitle: "选择一个以获得推荐。", start_btn: "开始", mixer_title: "调整音量", main_volume: "主音量", background_volume: "背景音量", turn_off_all: "关闭所有背景音", language_title: "选择语言", sleep_timer_title: "睡眠定时器", sleep_timer_remaining: "剩余时间", sleep_timer_15m: "15分钟", sleep_timer_30m: "30分钟", sleep_timer_60m: "60分钟", sleep_timer_custom: "自定义", sleep_timer_set: "设置计时器", sleep_timer_cancel: "取消计时器", start_listening_btn: "开始聆听", continue_without_timer: "无计时器继续", select_sleep_timer_title: "设置睡眠定时器", select_sleep_timer_subtitle: "在设定时间后自动停止播放。", mixer_onboarding_title: "混合背景音", mixer_onboarding_subtitle: "增强您的体验。（可选）", feedback_title: "您的体验如何？", feedback_yes: "我喜欢！", feedback_no: "不适合我", feedback_thanks_title: "太好了！", feedback_share_prompt: "帮助他人找到平静。与您的朋友分享此应用。", feedback_share_button: "分享", share_message_title: "轻松旋律播放器", share_message_text: "我正在使用此应用放松和专注。您可能也会喜欢！", feedback_close_button: "关闭", album_solfeggio: "视唱练耳频率", album_binaural: "双耳节拍", install_app: "安装应用" },
  ja: { goal_title: "あなたの目標は？", goal_subtitle: "一つ選択して推薦を得る。", start_btn: "開始", mixer_title: "音量調整", main_volume: "主音量", background_volume: "背景音量", turn_off_all: "すべての背景音をオフ", language_title: "言語を選択", sleep_timer_title: "スリープタイマー", sleep_timer_remaining: "残り時間", sleep_timer_15m: "15分", sleep_timer_30m: "30分", sleep_timer_60m: "60分", sleep_timer_custom: "カスタム", sleep_timer_set: "タイマーを設定", sleep_timer_cancel: "タイマーをキャンセル", start_listening_btn: "リスニング開始", continue_without_timer: "タイマーなしで続行", select_sleep_timer_title: "スリープタイマーを設定", select_sleep_timer_subtitle: "設定時間後に再生を自動的に停止します。", mixer_onboarding_title: "背景音をミックス", mixer_onboarding_subtitle: "あなたの体験を向上させます。（オプション）", feedback_title: "セッションはいかがでしたか？", feedback_yes: "大好き！", feedback_no: "私には合わない", feedback_thanks_title: "素晴らしい！", feedback_share_prompt: "他の人が落ち着きを見つけるのを手伝ってください。このアプリを友達と共有してください。", feedback_share_button: "共有", share_message_title: "リラックスメロディープレーヤー", share_message_text: "私はこのアプリを使ってリラックスし、集中しています。あなたも好きかもしれません！", feedback_close_button: "閉じる", album_solfeggio: "ソルフェジオ周波数", album_binaural: "バイノーラルビート", install_app: "インストール" },
  ko: { goal_title: "당신의 목표는?", goal_subtitle: "추천을 받으려면 하나를 선택。", start_btn: "시작", mixer_title: "볼륨 조절", main_volume: "메인 볼륨", background_volume: "배경 볼륨", turn_off_all: "모든 배경 사운드 끄기", language_title: "언어 선택", sleep_timer_title: "수면 타이머", sleep_timer_remaining: "남은 시간", sleep_timer_15m: "15분", sleep_timer_30m: "30분", sleep_timer_60m: "60분", sleep_timer_custom: "사용자 정의", sleep_timer_set: "타이머 설정", sleep_timer_cancel: "타이머 취소", start_listening_btn: "듣기 시작", continue_without_timer: "타이머 없이 계속", select_sleep_timer_title: "수면 타이머 설정", select_sleep_timer_subtitle: "설정된 시간 후에 자동으로 재생을 중지합니다。", mixer_onboarding_title: "배경 사운드 믹싱", mixer_onboarding_subtitle: "경험을 향상시키십시오. (선택 사항)", feedback_title: "세션은 어땠나요?", feedback_yes: "정말 좋았어요!", feedback_no: "저에게는 맞지 않아요", feedback_thanks_title: "멋져요!", feedback_share_prompt: "다른 사람들이 평온을 찾도록 도와주세요. 이 앱을 친구들과 공유하세요.", feedback_share_button: "공유", share_message_title: "편안한 멜로디 플레이어", share_message_text: "저는 이 앱을 사용하여 긴장을 풀고 집중하고 있습니다. 당신도 좋아할 수 있습니다!", feedback_close_button: "닫기", album_solfeggio: "솔페지오 주파수", album_binaural: "바이노럴 비트", install_app: "앱 설치" },
  fr: { goal_title: "Quel est votre but?", goal_subtitle: "Sélectionnez-en un pour une suggestion.", start_btn: "Commencer", mixer_title: "Ajuster le volume", main_volume: "Volume principal", background_volume: "Volume de fond", turn_off_all: "Désactiver tous les sons de fond", language_title: "Choisir la langue", sleep_timer_title: "Minuterie de sommeil", sleep_timer_remaining: "Temps restant", sleep_timer_15m: "15 Minutes", sleep_timer_30m: "30 Minutes", sleep_timer_60m: "60 Minutes", sleep_timer_custom: "Personnalisé", sleep_timer_set: "Régler la minuterie", sleep_timer_cancel: "Annuler la minuterie", start_listening_btn: "Commencer à écouter", continue_without_timer: "Continuer sans minuterie", select_sleep_timer_title: "Définir une minuterie de sommeil", select_sleep_timer_subtitle: "Arrête automatiquement la lecture après une durée définie.", mixer_onboarding_title: "Mixer les sons de fond", mixer_onboarding_subtitle: "Améliorez votre expérience. (Optionnel)", feedback_title: "Comment était votre session ?", feedback_yes: "J'ai adoré !", feedback_no: "Pas pour moi", feedback_thanks_title: "C'est génial !", feedback_share_prompt: "Aidez les autres à trouver leur calme. Partagez cette application avec vos amis.", feedback_share_button: "Partager", share_message_title: "Lecteur de mélodies relaxantes", share_message_text: "J'utilise cette application pour me détendre et me concentrer. Vous pourriez l'aimer aussi !", feedback_close_button: "Fermer", album_solfeggio: "Fréquences Solfeggio", album_binaural: "Battements Binauraux", install_app: "Installer" },
  de: { goal_title: "Was ist dein Ziel?", goal_subtitle: "Wähle eines für eine Empfehlung.", start_btn: "Start", mixer_title: "Lautstärke anpassen", main_volume: "Hauptlautstärke", background_volume: "Hintergrundlautstärke", turn_off_all: "Alle Hintergrundgeräusche ausschalten", language_title: "Sprache auswählen", sleep_timer_title: "Schlaf-Timer", sleep_timer_remaining: "Verbleibende Zeit", sleep_timer_15m: "15 Minuten", sleep_timer_30m: "30 Minuten", sleep_timer_60m: "60 Minuten", sleep_timer_custom: "Benutzerdefiniert", sleep_timer_set: "Timer einstellen", sleep_timer_cancel: "Timer abbrechen", start_listening_btn: "Zuhören beginnen", continue_without_timer: "Ohne Timer fortfahren", select_sleep_timer_title: "Schlaf-Timer einstellen", select_sleep_timer_subtitle: "Stoppt die Wiedergabe automatisch nach einer festgelegten Zeit.", mixer_onboarding_title: "Hintergrundgeräusche mischen", mixer_onboarding_subtitle: "Verbessern Sie Ihr Erlebnis. (Optional)", feedback_title: "Wie war Ihre Sitzung?", feedback_yes: "Ich fand es toll!", feedback_no: "Nichts für mich", feedback_thanks_title: "Das ist großartig!", feedback_share_prompt: "Helfen Sie anderen, ihre Ruhe zu finden. Teilen Sie diese App mit Ihren Freunden.", feedback_share_button: "Teilen", share_message_title: "Entspannender Melodie-Player", share_message_text: "Ich benutze diese App, um mich zu entspannen und zu konzentrieren. Sie könnte Ihnen auch gefallen!", feedback_close_button: "Schließen", album_solfeggio: "Solfeggio-Frequenzen", album_binaural: "Binaurale Beats", install_app: "Installieren" },
  es: { goal_title: "¿Cuál es tu objetivo?", goal_subtitle: "Selecciona uno para una recomendación.", start_btn: "Empezar", mixer_title: "Ajustar volumen", main_volume: "Volumen principal", background_volume: "Volumen de fondo", turn_off_all: "Apagar todos los sonidos de fondo", language_title: "Seleccionar idioma", sleep_timer_title: "Temporizador de sueño", sleep_timer_remaining: "Tiempo restante", sleep_timer_15m: "15 Minutos", sleep_timer_30m: "30 Minutos", sleep_timer_60m: "60 Minutos", sleep_timer_custom: "Personalizado", sleep_timer_set: "Establecer temporizador", sleep_timer_cancel: "Cancelar temporizador", start_listening_btn: "Comenzar a escuchar", continue_without_timer: "Continuar sin temporizador", select_sleep_timer_title: "Establecer temporizador de sueño", select_sleep_timer_subtitle: "Detiene la reproducción automáticamente después de un tiempo establecido.", mixer_onboarding_title: "Mezclar sonidos de fondo", mixer_onboarding_subtitle: "Mejore su experiencia. (Opcional)", feedback_title: "¿Cómo fue tu sesión?", feedback_yes: "¡Me encantó!", feedback_no: "No es para mí", feedback_thanks_title: "¡Eso es genial!", feedback_share_prompt: "Ayuda a otros a encontrar la calma. Comparte esta aplicación con tus amigos.", feedback_share_button: "Compartir", share_message_title: "Reproductor de melodías relajantes", share_message_text: "Estoy usando esta aplicación para relajarme y concentrarme. ¡Quizás a ti también te guste!", feedback_close_button: "Cerrar", album_solfeggio: "Frecuencias de Solfeo", album_binaural: "Sonidos Binaurales", install_app: "Instalar" },
};

export const languages: Language[] = [
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' }, { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' }, { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' }, { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' }, { code: 'es', name: 'Español', flag: '🇪🇸' },
];

export const goals: GoalsData = {
  healing_pain: { icon: '❤️‍🩹', recommendation: { type: 'solfeggio', index: 0 } }, // 174 Hz
  focus: { icon: '🎯', recommendation: { type: 'binaural', index: 3 } }, // Beta
  relax: { icon: '🧘', recommendation: { type: 'solfeggio', index: 4 } }, // 432Hz
  sleep: { icon: '😴', recommendation: { type: 'binaural', index: 0 } }, // Delta
  meditate: { icon: '🕉️', recommendation: { type: 'binaural', index: 1 } }, // Theta
  tinnitus: { icon: '👂', recommendation: { type: 'mixer', id: 'white_noise' } }, // White Noise
};

// FIX: Moved translations from the 'goals' object into a new 'goalTranslations' constant
// to resolve a TypeScript type conflict with the GoalsData interface.
export const goalTranslations = {
  en: { healing_pain: "Healing Pain", focus: "Focus", relax: "Relax", sleep: "Sleep", meditate: "Meditate", tinnitus: "Tinnitus" },
  vi: { healing_pain: "Chữa lành nỗi đau", focus: "Tập trung", relax: "Thư giãn", sleep: "Ngủ", meditate: "Thiền", tinnitus: "Ù tai" },
  zh: { healing_pain: "治愈痛苦", focus: "专注", relax: "放松", sleep: "睡觉", meditate: "冥想", tinnitus: "耳鸣" },
  ja: { healing_pain: "痛みの癒し", focus: "集中", relax: "リラックス", sleep: "睡眠", meditate: "瞑想", tinnitus: "耳鳴り" },
  ko: { healing_pain: "고통 치유", focus: "집중", relax: "휴식", sleep: "수면", meditate: "명상", tinnitus: "이명" },
  fr: { healing_pain: "Guérir la douleur", focus: "Concentration", relax: "Détente", sleep: "Sommeil", meditate: "Méditation", tinnitus: "Acouphènes" },
  de: { healing_pain: "Schmerzheilung", focus: "Fokus", relax: "Entspannen", sleep: "Schlaf", meditate: "Meditieren", tinnitus: "Tinnitus" },
  es: { healing_pain: "Sanar el dolor", focus: "Concentración", relax: "Relajarse", sleep: "Dormir", meditate: "Meditar", tinnitus: "Tinnitus" },
};

export const solfeggioFrequencies: SolfeggioFrequency[] = [
    { freq: 174, name: { vi: "174 Hz An Toàn", en: "174 Hz Security" }, short_benefit: { vi: "Giảm đau & căng thẳng", en: "Reduces pain & stress" }, long_benefits: { en: ["Reduces physical pain and alleviates tension.", "Creates a sense of security and safety in your environment.", "A natural anaesthetic, beneficial for deep relaxation."], vi: ["Giảm đau nhức cơ thể và giải tỏa căng thẳng.", "Tạo ra cảm giác an toàn và được che chở.", "Là một liều thuốc giảm đau tự nhiên, tốt cho việc thư giãn sâu."] }, synth_hint: { envelope: { attack:0.2, decay:1.2, sustain:0.6, release:1.5}, lowpass_hz: 6000 } },
    { freq: 285, name: { vi: "285 Hz Chữa Lành", en: "285 Hz Healing" }, short_benefit: { vi: "Chữa lành mô & cơ quan", en: "Heals tissues & organs" }, long_benefits: { en: ["Aids in healing tissues and rejuvenating organs.", "Helps restore cellular health and energy fields.", "Ideal for recovering from injuries and boosting vitality."], vi: ["Hỗ trợ chữa lành các mô và phục hồi cơ quan.", "Giúp khôi phục sức khỏe tế bào và trường năng lượng.", "Lý tưởng để phục hồi sau chấn thương và tăng cường sinh lực."] }, synth_hint: { envelope: { attack:0.15, decay:1.0, sustain:0.5, release:1.2}, lowpass_hz: 5500 } },
    { freq: 396, name: { vi: "396 Hz Giải Phóng", en: "396 Hz Liberation" }, short_benefit: { vi: "Giải phóng sợ hãi & tội lỗi", en: "Liberates from fear & guilt" }, long_benefits: { en: ["Liberates you from feelings of guilt and fear.", "Helps to clear subconscious negative beliefs.", "Grounding and cleansing for the root chakra."], vi: ["Giải phóng bạn khỏi cảm giác tội lỗi và sợ hãi.", "Giúp xóa bỏ những niềm tin tiêu cực trong tiềm thức.", "Tiếp đất và thanh lọc cho luân xa gốc."] }, synth_hint: { envelope: { attack:0.1, decay:0.8, sustain:0.6, release:1.0}, lowpass_hz: 7000 } },
    { freq: 417, name: { vi: "417 Hz Thay Đổi", en: "417 Hz Change" }, short_benefit: { vi: "Hóa giải tiêu cực", en: "Facilitates change" }, long_benefits: { en: ["Helps to undo negative situations and facilitate positive change.", "Cleanses traumatic experiences and clears destructive influences.", "Energizes your cells and promotes a fresh start."], vi: ["Giúp đảo ngược tình huống tiêu cực và tạo điều kiện cho thay đổi tích cực.", "Thanh lọc trải nghiệm đau thương và xóa bỏ ảnh hưởng xấu.", "Tiếp năng lượng cho tế bào và thúc đẩy một khởi đầu mới."] }, synth_hint: { envelope: { attack:0.1, decay:0.8, sustain:0.5, release:1.0} } },
    { freq: 432, name: { vi: "432 Hz Hài Hòa", en: "432 Hz Harmony" }, short_benefit: { vi: "Hài hòa với tự nhiên", en: "Harmonizes with nature" }, long_benefits: { en: ["Aligns your mind with the harmonious vibrations of nature.", "Promotes a sense of peace and well-being.", "Known as the 'heartbeat of the Earth' for its calming effects."], vi: ["Điều chỉnh tâm trí bạn với những rung động hài hòa của tự nhiên.", "Mang lại cảm giác bình yên và khỏe mạnh.", "Được biết đến là 'nhịp đập của Trái Đất' vì tác dụng làm dịu."] }, synth_hint: { envelope: { attack:0.12, decay:1.2, sustain:0.6, release:1.2}, lowpass_hz: 6500 } },
    { freq: 528, name: { vi: "528 Hz Tình Yêu", en: "528 Hz Love" }, short_benefit: { vi: "Sửa chữa DNA, tình yêu", en: "Repairs DNA, brings love" }, long_benefits: { en: ["Known as the 'love frequency' for its connection to miracles.", "Promotes DNA repair and increases life energy.", "Brings transformation and miracles into your life."], vi: ["Được gọi là 'tần số tình yêu' vì liên quan đến phép màu.", "Thúc đẩy sửa chữa DNA và tăng cường năng lượng sống.", "Mang lại sự chuyển hóa và những điều kỳ diệu cho cuộc sống."] }, synth_hint: { envelope: { attack:0.2, decay:1.3, sustain:0.5, release:1.5} } },
    { freq: 639, name: { vi: "639 Hz Kết Nối", en: "639 Hz Connection" }, short_benefit: { vi: "Hàn gắn mối quan hệ", en: "Heals relationships" }, long_benefits: { en: ["Enhances communication, understanding, and tolerance.", "Helps in healing and reconnecting relationships.", "Promotes harmony within family and social circles."], vi: ["Cải thiện giao tiếp, sự thấu hiểu và lòng bao dung.", "Giúp hàn gắn và kết nối lại các mối quan hệ.", "Tạo ra sự hòa hợp trong gia đình và các mối quan hệ xã hội."] }, synth_hint: { envelope: { attack:0.2, decay:1.1, sustain:0.6, release:1.4} } },
    { freq: 741, name: { vi: "741 Hz Thức Tỉnh", en: "741 Hz Awakening" }, short_benefit: { vi: "Đánh thức trực giác", en: "Awakens intuition" }, long_benefits: { en: ["Cleanses the body from toxins and electromagnetic radiation.", "Promotes self-expression and awakens intuition.", "Leads to a healthier, simpler life by solving problems."], vi: ["Thanh lọc cơ thể khỏi độc tố và bức xạ điện từ.", "Thúc đẩy sự thể hiện bản thân và đánh thức trực giác.", "Dẫn đến một cuộc sống lành mạnh, đơn giản hơn bằng cách giải quyết vấn đề."] }, synth_hint: { envelope: { attack:0.12, decay:0.9, sustain:0.5, release:1.2} } },
    { freq: 852, name: { vi: "852 Hz Tâm Linh", en: "852 Hz Spiritual" }, short_benefit: { vi: "Trở về trật tự tâm linh", en: "Returns to spiritual order" }, long_benefits: { en: ["Awakens intuition and helps you return to spiritual order.", "Raises cellular energy and awareness.", "Connects you to your higher self and universal consciousness."], vi: ["Đánh thức trực giác và giúp bạn trở về với trật tự tâm linh.", "Nâng cao năng lượng tế bào và nhận thức.", "Kết nối bạn với bản thể cao hơn và ý thức vũ trụ."] }, synth_hint: { envelope: { attack:0.15, decay:1.0, sustain:0.5, release:1.2} } },
    { freq: 963, name: { vi: "963 Hz Nguồn Cội", en: "963 Hz Source" }, short_benefit: { vi: "Kết nối năng lượng vũ trụ", en: "Connects to universal energy" }, long_benefits: { en: ["Activates the pineal gland, connecting you to the source.", "Known as the 'frequency of the gods', it awakens the crown chakra.", "Helps you experience oneness and universal energy."], vi: ["Kích hoạt tuyến tùng, kết nối bạn với cội nguồn.", "Được gọi là 'tần số của các vị thần', đánh thức luân xa vương miện.", "Giúp bạn trải nghiệm sự hợp nhất và năng lượng vũ trụ."] }, synth_hint: { envelope: { attack:0.2, decay:1.2, sustain:0.5, release:1.6} } },
];

export const binauralBeats: BinauralBeat[] = [
    { delta: 3, baseFreq: 111, name: { vi: "Sóng Delta", en: "Delta Waves" }, short_benefit: { vi: "Giấc ngủ sâu", en: "Deep sleep" }, long_benefits: { en: ["Promotes deep, restorative sleep and pain relief.", "Essential for dreamless sleep and immune system health.", "Helps access the unconscious mind and deep relaxation."], vi: ["Thúc đẩy giấc ngủ sâu, phục hồi và giảm đau.", "Cần thiết cho giấc ngủ không mơ và sức khỏe hệ miễn dịch.", "Giúp tiếp cận tiềm thức và thư giãn sâu."] }, synth_hint: { left_freq_hz: 111, right_freq_hz: 114, safe_lowpass_hz: 8000 } },
    { delta: 6, baseFreq: 120, name: { vi: "Sóng Theta", en: "Theta Waves" }, short_benefit: { vi: "Thiền định & sáng tạo", en: "Meditation & creativity" }, long_benefits: { en: ["Enhances creativity, meditation, and deep relaxation.", "Improves memory and increases intuitive insights.", "Ideal for REM sleep, learning, and stress reduction."], vi: ["Tăng cường sự sáng tạo, thiền định và thư giãn sâu.", "Cải thiện trí nhớ và tăng cường trực giác.", "Lý tưởng cho giấc ngủ REM, học tập và giảm căng thẳng."] }, synth_hint: { left_freq_hz: 120, right_freq_hz: 126, safe_lowpass_hz: 9000 } },
    { delta: 10, baseFreq: 180, name: { vi: "Sóng Alpha", en: "Alpha Waves" }, short_benefit: { vi: "Thư thái, tích cực", en: "Relaxed positivity" }, long_benefits: { en: ["Encourages a state of calm, relaxed alertness.", "Reduces stress and anxiety, promoting positivity.", "The gateway to meditation and a bridge to the subconscious."], vi: ["Khuyến khích trạng thái tỉnh táo, thư thái và bình tĩnh.", "Giảm căng thẳng và lo âu, thúc đẩy sự tích cực.", "Là cánh cổng dẫn đến thiền định và là cầu nối với tiềm thức."] }, synth_hint: { left_freq_hz: 180, right_freq_hz: 190, safe_lowpass_hz: 10000 } },
    { delta: 20, baseFreq: 220, name: { vi: "Sóng Beta", en: "Beta Waves" }, short_benefit: { vi: "Tập trung & tỉnh táo", en: "Focus & alertness" }, long_benefits: { en: ["Increases focus, alertness, and problem-solving abilities.", "Enhances cognitive function and concentration.", "Perfect for active thinking, studying, or complex tasks."], vi: ["Tăng cường sự tập trung, tỉnh táo và khả năng giải quyết vấn đề.", "Cải thiện chức năng nhận thức và sự tập trung.", "Hoàn hảo cho việc tư duy tích cực, học tập hoặc các công việc phức tạp."] }, synth_hint: { left_freq_hz: 220, right_freq_hz: 240, safe_lowpass_hz: 11000 } },
    { delta: 40, baseFreq: 300, name: { vi: "Sóng Gamma", en: "Gamma Waves" }, short_benefit: { vi: "Học tập & trí nhớ", en: "Learning & memory" }, long_benefits: { en: ["Boosts learning, memory recall, and information processing.", "Associated with peak concentration and high-level cognition.", "Enhances perception and problem-solving skills."], vi: ["Tăng cường khả năng học tập, ghi nhớ và xử lý thông tin.", "Liên quan đến sự tập trung cao độ và nhận thức cấp cao.", "Cải thiện nhận thức và kỹ năng giải quyết vấn-đề."] }, synth_hint: { left_freq_hz: 300, right_freq_hz: 340, safe_lowpass_hz: 12000 } }
];

const originalIcons: { [key: string]: string } = {
  white_noise: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>`,
  pink_noise: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>`,
  brown_noise: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2h10a2 2 0 002-2v-1a2 2 0 012-2h1.945" /></svg>`,
  rain: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10" /></svg>`,
  ocean_waves: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" /></svg>`,
  wind: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>`,
  fire: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7C14 5 16.09 5.777 17.657 7.343A8 8 0 0117.657 18.657z" /><path stroke-linecap="round" stroke-linejoin="round" d="M9.879 16.121A3 3 0 1014.12 11.88a3 3 0 00-4.242 4.242z" /></svg>`,
  stream: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16m-7 6h7" /></svg>`,
  tuning_forks_spatial: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 19V6.5a3.5 3.5 0 117 0V19M12 19v-2" /></svg>`,
  forest: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21V8m-4 4l4-4 4 4m-8 8h8" /></svg>`
};

export const naturalSounds: NaturalSound[] = [
  { id: "white_noise", type: "noise", noise_type: "white", icon: originalIcons.white_noise, name: { vi: "Ồn trắng", en: "White Noise" } },
  { id: "pink_noise", type: "noise", noise_type: "pink", icon: originalIcons.pink_noise, name: { vi: "Ồn hồng", en: "Pink Noise" } },
  { id: "brown_noise", type: "noise", noise_type: "brown", icon: originalIcons.brown_noise, name: { vi: "Ồn nâu", en: "Brown Noise" } },
  { id: "rain", type: "filtered_noise", noise_type: "pink", filter_freq: 1200, icon: originalIcons.rain, name: { vi: "Mưa", en: "Rain" } },
  { id: "ocean_waves", type: "lfo_noise", noise_type: "pink", lfo_freq: "8n", icon: originalIcons.ocean_waves, name: { vi: "Sóng biển", en: "Ocean Waves" } },
  { id: "wind", type: "lfo_noise", noise_type: "brown", lfo_freq: "4n", icon: originalIcons.wind, name: { vi: "Gió", en: "Wind" } },
  { id: "fire", type: "fire", icon: originalIcons.fire, name: { vi: "Lửa", en: "Fire" } },
  { id: "stream", type: "filtered_noise", noise_type: "white", filter_freq: 2000, icon: originalIcons.stream, name: { vi: "Suối", en: "Stream" } },
  { id: "tuning_forks_spatial", type: "tuning_forks_spatial", icon: originalIcons.tuning_forks_spatial, name: { vi: "Âm Thoa 3D", en: "Spatial Forks" } },
  { id: "forest", type: "forest", icon: originalIcons.forest, name: { vi: "Rừng rậm", en: "Forest", zh: "森林", ja: "森林", ko: "숲", fr: "Forêt", de: "Wald", es: "Bosque" } },
  { id: "gentle_stream", type: "filtered_noise", noise_type: "pink", filter_freq: 1600, icon: originalIcons.stream, name: { vi: "Suối nhẹ", en: "Gentle Stream", zh: "潺潺溪流", ja: "穏やかな小川", ko: "부드러운 시냇물", fr: "Doux Ruisseau", de: "Sanfter Bach", es: "Arroyo Suave" } },
];