import type { ShareTemplates } from './types';

export const shareTemplates: ShareTemplates = {
  healing_pain: {
    en: { title: "A moment of relief and healing ✨", text: "Just tried the 'Healing Pain' session on this app. The 174 Hz frequency is incredibly soothing. If you need to ease some tension, you should check it out. {url}" },
    vi: { title: "Một khoảnh khắc nhẹ nhõm và chữa lành ✨", text: "Vừa thử phiên 'Chữa lành nỗi đau' trên ứng dụng này. Tần số 174 Hz thật sự rất êm dịu. Nếu bạn cần giải tỏa căng thẳng, hãy thử xem sao nhé. {url}" },
    zh: { title: "片刻的缓解与治愈 ✨", text: "刚刚试了这个应用程序上的“治愈痛苦”环节。174赫兹的频率令人难以置信地舒缓。如果你需要缓解一些紧张情绪，你应该试试看。 {url}" },
    ja: { title: "安らぎと癒しのひととき ✨", text: "このアプリで「痛みの癒し」セッションを試しました。174Hzの周波数は信じられないほど心地よいです。緊張を和らげたいなら、ぜひチェックしてみてください。 {url}" },
    ko: { title: "안도와 치유의 순간 ✨", text: "방금 이 앱에서 '고통 치유' 세션을 시도해 봤습니다. 174Hz 주파수는 믿을 수 없을 정도로 진정됩니다. 긴장을 풀고 싶다면 확인해보세요. {url}" },
    fr: { title: "Un moment de soulagement et de guérison ✨", text: "Je viens d'essayer la session 'Guérir la douleur' sur cette application. La fréquence de 174 Hz est incroyablement apaisante. Si vous avez besoin de soulager une certaine tension, vous devriez l'essayer. {url}" },
    de: { title: "Ein Moment der Linderung und Heilung ✨", text: "Habe gerade die 'Schmerzheilung'-Sitzung in dieser App ausprobiert. Die 174-Hz-Frequenz ist unglaublich beruhigend. Wenn du etwas Anspannung lösen musst, solltest du es dir ansehen. {url}" },
    es: { title: "Un momento de alivio y sanación ✨", text: "Acabo de probar la sesión 'Sanar el dolor' en esta aplicación. La frecuencia de 174 Hz es increíblemente relajante. Si necesitas aliviar algo de tensión, deberías echarle un vistazo. {url}" },
  },
  focus: {
    en: { title: "Locked in and focused 🎯", text: "The 'Focus' session with Beta waves on the Relaxing Melody app is a game-changer for my productivity. Sharing in case you need a boost too! {url}" },
    vi: { title: "Đã vào guồng và tập trung 🎯", text: "Phiên 'Tập trung' với sóng Beta trên ứng dụng Giai điệu Thư giãn thực sự thay đổi cuộc chơi cho năng suất của mình. Chia sẻเผื่อ bạn cũng cần một cú hích! {url}" },
    zh: { title: "锁定并专注 🎯", text: "在轻松旋律应用上使用Beta波的“专注”环节改变了我的生产力。分享给你，以防你也需要提升！ {url}" },
    ja: { title: "集中してロックイン 🎯", text: "リラックスメロディーアプリのベータ波を使った「集中」セッションは、私の生産性にとってゲームチェンジャーです。あなたもブーストが必要な場合に備えて共有します！ {url}" },
    ko: { title: "집중하고 몰입 🎯", text: "편안한 멜로디 앱의 베타파를 이용한 '집중' 세션은 제 생산성에 있어 게임 체인저입니다. 당신도 부스트가 필요할 경우를 대비해 공유합니다! {url}" },
    fr: { title: "Concentré et verrouillé 🎯", text: "La session 'Focus' avec les ondes Bêta sur l'application Relaxing Melody change la donne pour ma productivité. Je partage au cas où vous auriez aussi besoin d'un coup de pouce ! {url}" },
    de: { title: "Voll konzentriert 🎯", text: "Die 'Fokus'-Sitzung mit Beta-Wellen in der Relaxing Melody App ist ein Game-Changer für meine Produktivität. Ich teile das, falls du auch einen Schub brauchst! {url}" },
    es: { title: "Concentrado y enfocado 🎯", text: "La sesión de 'Enfoque' con ondas Beta en la aplicación Relaxing Melody es un cambio de juego para mi productividad. ¡Lo comparto por si tú también necesitas un impulso! {url}" },
  },
  relax: {
    en: { title: "Feeling so relaxed and centered 🧘", text: "This 'Relax' session (432 Hz) on the Relaxing Melody app just melted my stress away. It's like a reset button for your mind. Highly recommend it! {url}" },
    vi: { title: "Cảm thấy thật thư thái và cân bằng 🧘", text: "Phiên 'Thư giãn' (432 Hz) trên ứng dụng Giai điệu Thư giãn vừa làm tan biến hết căng thẳng của mình. Giống như một nút reset cho tâm trí vậy. Rất khuyến khích nhé! {url}" },
    zh: { title: "感觉如此放松和专注 🧘", text: "这款轻松旋律应用上的“放松”环节（432赫兹）刚刚消除了我的压力。这就像是你心灵的重置按钮。强烈推荐！ {url}" },
    ja: { title: "とてもリラックスして中心にいる気分 🧘", text: "リラックスメロディーアプリのこの「リラックス」セッション（432 Hz）は、私のストレスを溶かしてくれました。まるで心のリセットボタンのようです。強くお勧めします！ {url}" },
    ko: { title: "너무 편안하고 중심이 잡힌 느낌 🧘", text: "편안한 멜로디 앱의 이 '휴식' 세션(432Hz)은 제 스트레스를 녹여주었습니다. 마음의 리셋 버튼과 같습니다. 강력 추천합니다! {url}" },
    fr: { title: "Je me sens si détendu et centré 🧘", text: "Cette session 'Détente' (432 Hz) sur l'application Relaxing Melody a tout simplement fait fondre mon stress. C'est comme un bouton de réinitialisation pour votre esprit. Je la recommande vivement ! {url}" },
    de: { title: "Fühle mich so entspannt und zentriert 🧘", text: "Diese 'Entspannungs'-Sitzung (432 Hz) in der Relaxing Melody App hat meinen Stress einfach weggeschmolzen. Es ist wie ein Reset-Knopf für deinen Geist. Sehr zu empfehlen! {url}" },
    es: { title: "Sintiéndome tan relajado y centrado 🧘", text: "Esta sesión de 'Relajación' (432 Hz) en la aplicación Relaxing Melody acaba de derretir mi estrés. Es como un botón de reinicio para tu mente. ¡Lo recomiendo mucho! {url}" },
  },
  sleep: {
    en: { title: "Ready for some deep, restful sleep 😴", text: "The 'Sleep' session with Delta waves on the Relaxing Melody app is my new favorite way to wind down. If you have trouble sleeping, you have to try this. {url}" },
    vi: { title: "Sẵn sàng cho một giấc ngủ sâu và ngon 😴", text: "Phiên 'Ngủ' với sóng Delta trên ứng dụng Giai điệu Thư giãn là cách yêu thích mới của mình để thư giãn cuối ngày. Nếu bạn khó ngủ, bạn phải thử cái này. {url}" },
    zh: { title: "准备好进行深度、宁静的睡眠 😴", text: "在轻松旋律应用上使用Delta波的“睡眠”环节是我最喜欢的放松方式。如果你有睡眠困难，你必须试试这个。 {url}" },
    ja: { title: "深く安らかな眠りの準備ができました 😴", text: "リラックスメロディーアプリのデルタ波を使った「睡眠」セッションは、私の新しいお気に入りのくつろぎ方です。もし睡眠に問題があるなら、これを試してみるべきです。 {url}" },
    ko: { title: "깊고 편안한 잠을 잘 준비가 되었습니다 😴", text: "편안한 멜로디 앱의 델타파를 이용한 '수면' 세션은 제가 가장 좋아하는 새로운 휴식 방법입니다. 수면에 어려움이 있다면 꼭 시도해보세요. {url}" },
    fr: { title: "Prêt pour un sommeil profond et réparateur 😴", text: "La session 'Sommeil' avec les ondes Delta sur l'application Relaxing Melody est ma nouvelle façon préférée de me détendre. Si vous avez des problèmes de sommeil, vous devez essayer ceci. {url}" },
    de: { title: "Bereit für tiefen, erholsamen Schlaf 😴", text: "Die 'Schlaf'-Sitzung mit Delta-Wellen in der Relaxing Melody App ist meine neue Lieblingsmethode zum Entspannen. Wenn du Schlafprobleme hast, musst du das ausprobieren. {url}" },
    es: { title: "Listo para un sueño profundo y reparador 😴", text: "La sesión de 'Sueño' con ondas Delta en la aplicación Relaxing Melody es mi nueva forma favorita de relajarme. Si tienes problemas para dormir, tienes que probar esto. {url}" },
  },
  meditate: {
    en: { title: "A peaceful meditation session 🕉️", text: "Just had a deep meditation with Theta waves using the Relaxing Melody app. Feeling so clear and connected. Sharing the good vibes with you! {url}" },
    vi: { title: "Một buổi thiền thật bình yên 🕉️", text: "Vừa có một buổi thiền sâu với sóng Theta bằng ứng dụng Giai điệu Thư giãn. Cảm thấy thật minh mẫn và kết nối. Chia sẻ những rung cảm tốt đẹp này với bạn! {url}" },
    zh: { title: "一次宁静的冥想环节 🕉️", text: "刚刚使用轻松旋律应用与Theta波进行了一次深度冥想。感觉如此清晰和连接。与你分享这份美好的感觉！ {url}" },
    ja: { title: "平和な瞑想セッション 🕉️", text: "リラックスメロディーアプリを使ってシータ波で深い瞑想をしました。とてもクリアでつながっている感じがします。あなたと良い雰囲気を共有します！ {url}" },
    ko: { title: "평화로운 명상 세션 🕉️", text: "방금 편안한 멜로디 앱을 사용하여 세타파로 깊은 명상을 했습니다. 너무 명료하고 연결된 느낌입니다. 당신과 좋은 기운을 나눕니다! {url}" },
    fr: { title: "Une séance de méditation paisible 🕉️", text: "Je viens d'avoir une méditation profonde avec les ondes Thêta en utilisant l'application Relaxing Melody. Je me sens si clair et connecté. Je partage les bonnes vibrations avec vous ! {url}" },
    de: { title: "Eine friedliche Meditationssitzung 🕉️", text: "Hatte gerade eine tiefe Meditation mit Theta-Wellen mit der Relaxing Melody App. Fühle mich so klar und verbunden. Ich teile die guten Schwingungen mit dir! {url}" },
    es: { title: "Una sesión de meditación pacífica 🕉️", text: "Acabo de tener una meditación profunda con ondas Theta usando la aplicación Relaxing Melody. Sintiéndome tan claro y conectado. ¡Compartiendo las buenas vibras contigo! {url}" },
  },
  tinnitus: {
    en: { title: "Found some relief from ringing ears 🎧", text: "The 'Tinnitus' session with white noise on the Relaxing Melody app has been so helpful. If you deal with ringing sounds, this might bring you some peace. {url}" },
    vi: { title: "Tìm thấy chút nhẹ nhõm khỏi tiếng ù tai 🎧", text: "Phiên 'Ù tai' với tiếng ồn trắng trên ứng dụng Giai điệu Thư giãn thật sự hữu ích. Nếu bạn cũng bị tiếng ù trong tai, cái này có thể mang lại cho bạn chút bình yên. {url}" },
    zh: { title: "从耳鸣中找到了一些缓解 🎧", text: "轻松旋律应用上带有白噪音的“耳鸣”环节非常有帮助。如果你有耳鸣的困扰，这可能会给你带来一些平静。 {url}" },
    ja: { title: "耳鳴りからの解放を見つけました 🎧", text: "リラックスメロディーアプリのホワイトノイズを使った「耳鳴り」セッションはとても役立ちました。もし耳鳴りに悩んでいるなら、これはあなたに平穏をもたらすかもしれません。 {url}" },
    ko: { title: "귀울림으로부터의 안도감을 찾았습니다 🎧", text: "편안한 멜로디 앱의 백색 소음을 이용한 '이명' 세션은 매우 도움이 되었습니다. 만약 당신이 귀울림 소리로 고생한다면, 이것이 당신에게 평화를 가져다 줄 수 있습니다. {url}" },
    fr: { title: "J'ai trouvé un certain soulagement des acouphènes 🎧", text: "La session 'Acouphènes' avec bruit blanc sur l'application Relaxing Melody a été très utile. Si vous avez des bourdonnements, cela pourrait vous apporter un peu de paix. {url}" },
    de: { title: "Etwas Linderung bei Ohrensausen gefunden 🎧", text: "Die 'Tinnitus'-Sitzung mit weißem Rauschen in der Relaxing Melody App war so hilfreich. Wenn du mit Klingelgeräuschen zu tun hast, könnte dir das etwas Frieden bringen. {url}" },
    es: { title: "Encontré algo de alivio para el zumbido de oídos 🎧", text: "La sesión de 'Tinnitus' con ruido blanco en la aplicación Relaxing Melody ha sido de gran ayuda. Si lidias con zumbidos, esto podría traerte algo de paz. {url}" },
  },
  generic: {
    en: { title: "Find your calm with Relaxing Melody 🎶", text: "I'm using this amazing app to generate personalized soundscapes for relaxation and focus. Thought you might love it too! {url}" },
    vi: { title: "Tìm lại sự bình yên với Giai điệu Thư giãn 🎶", text: "Mình đang dùng ứng dụng tuyệt vời này để tạo ra các không gian âm thanh cá nhân hóa cho việc thư giãn và tập trung. Nghĩ là bạn cũng sẽ thích nó! {url}" },
    zh: { title: "用轻松旋律找到你的平静 🎶", text: "我正在使用这个神奇的应用程序生成个性化的音景，以放松和专注。我想你可能也会喜欢它！ {url}" },
    ja: { title: "リラックスメロディーであなたの静けさを見つけよう 🎶", text: "私はこの素晴らしいアプリを使って、リラクゼーションと集中のためのパーソナライズされたサウンドスケープを生成しています。あなたもきっと気に入ると思いました！ {url}" },
    ko: { title: "편안한 멜로디로 평온을 찾으세요 🎶", text: "저는 이 놀라운 앱을 사용하여 휴식과 집중을 위한 개인화된 사운드스케이프를 생성하고 있습니다. 당신도 좋아할 것 같아서요! {url}" },
    fr: { title: "Trouvez votre calme avec Relaxing Melody 🎶", text: "J'utilise cette application incroyable pour générer des paysages sonores personnalisés pour la relaxation et la concentration. J'ai pensé que vous pourriez aussi l'adorer ! {url}" },
    de: { title: "Finde deine Ruhe mit Relaxing Melody 🎶", text: "Ich benutze diese erstaunliche App, um personalisierte Klanglandschaften zur Entspannung und Konzentration zu erstellen. Dachte, du könntest sie auch lieben! {url}" },
    es: { title: "Encuentra tu calma con Relaxing Melody 🎶", text: "Estoy usando esta increíble aplicación para generar paisajes sonoros personalizados para la relajación y la concentración. ¡Pensé que a ti también te encantaría! {url}" },
  }
};