import type { SolfeggioFrequency, BinauralBeat, NaturalSound } from './types';

export const solfeggioFrequencies: SolfeggioFrequency[] = [
    { freq: 174, name: { vi: "174 Hz An Toàn", en: "174 Hz Security" }, short_benefit: { vi: "Giảm đau & căng thẳng", en: "Reduces pain & stress" }, long_benefits: { en: ["Reduces physical pain and alleviates tension.", "Creates a sense of security and safety in your environment.", "A natural anaesthetic, beneficial for deep relaxation."], vi: ["Giảm đau nhức cơ thể và giải tỏa căng thẳng.", "Tạo ra cảm giác an toàn và được che chở.", "Là một liều thuốc giảm đau tự nhiên, tốt cho việc thư giãn sâu."] }, synth_hint: { envelope: { attack:0.2, decay:1.2, sustain:0.6, release:1.5}, lowpass_hz: 6000 } },
    { freq: 285, name: { vi: "285 Hz Chữa Lành", en: "285 Hz Healing" }, short_benefit: { vi: "Chữa lành mô & cơ quan", en: "Heals tissues & organs" }, long_benefits: { en: ["Aids in healing tissues and rejuvenating organs.", "Helps restore cellular health and energy fields.", "Ideal for recovering from injuries and boosting vitality."], vi: ["Hỗ trợ chữa lành các mô và phục hồi cơ quan.", "Giúp khôi phục sức khỏe tế bào và trường năng lượng.", "Lý tưởng để phục hồi sau chấn thương và tăng cường sinh lực."] }, synth_hint: { envelope: { attack:0.15, decay:1.0, sustain:0.5, release:1.2}, lowpass_hz: 5500 } },
    { freq: 396, name: { vi: "396 Hz Giải Phóng", en: "396 Hz Liberation" }, short_benefit: { vi: "Giải phóng sợ hãi & tội lỗi", en: "Liberates from fear & guilt" }, long_benefits: { en: ["Liberates you from feelings of guilt and fear.", "Helps to clear subconscious negative beliefs.", "Grounding and cleansing for the root chakra."], vi: ["Giải phóng bạn khỏi cảm giác tội lỗi và sợ hãi.", "Giúp xóa bỏ những niềm tin tiêu cực trong tiềm thức.", "Tiếp đất và thanh lọc cho luân xa gốc."] }, synth_hint: { envelope: { attack:0.1, decay:0.8, sustain:0.6, release:1.0}, lowpass_hz: 7000 } },
    { freq: 417, name: { vi: "417 Hz Thay Đổi", en: "417 Hz Change" }, short_benefit: { vi: "Hóa giải tiêu cực", en: "Facilitates change" }, long_benefits: { en: ["Helps to undo negative situations and facilitate positive change.", "Cleanses traumatic experiences and clears destructive influences.", "Energizes your cells and promotes a fresh start."], vi: ["Giúp đảo ngược tình huống tiêu cực và tạo điều kiện cho thay đổi tích cực.", "Thanh lọc trải nghiệm đau thương và xóa bỏ ảnh hưởng xấu.", "Tiếp năng lượng cho tế bào và thúc đẩy một khởi đầu mới."] }, synth_hint: { envelope: { attack:0.1, decay:0.8, sustain:0.5, release:1.0} } },
    { freq: 432, name: { vi: "432 Hz Hài Hòa", en: "432 Hz Harmony" }, short_benefit: { vi: "Hài hòa với tự nhiên", en: "Harmonizes with nature" }, long_benefits: { en: ["Aligns your mind with the harmonious vibrations of nature.", "Promotes a sense of peace and well-being.", "Known as the 'heartbeat of the Earth' for its calming effects."], vi: ["Điều chỉnh tâm trí bạn với những rung động hài hòa của tự nhiên.", "Mang lại cảm giác bình yên và khỏe mạnh.", "Được biết đến là 'nhịp đập của Trái Đất' vì tác dụng làm dịu."] }, synth_hint: { envelope: { attack:0.12, decay:1.2, sustain:0.6, release:1.2}, lowpass_hz: 6500 } },
    { freq: 528, name: { vi: "528 Hz Tình Yêu", en: "528 Hz Love" }, short_benefit: { vi: "Sửa chữa DNA, tình yêu", en: "Repairs DNA, brings love" }, long_benefits: { en: ["Known as the 'love frequency' for its connection to miracles.", "Promotes DNA repair and increases life energy.", "Brings transformation and miracles into your life."], vi: ["Được gọi là 'tần số tình yêu' vì liên quan đến phép màu.", "Thúc đẩy sửa chữa DNA và tăng cường năng lượng sống.", "Mang lại sự chuyển hóa và những điều kỳ diệu cho cuộc sống."] }, synth_hint: { envelope: { attack:0.2, decay:1.3, sustain:0.5, release:1.5} } },
    { freq: 639, name: { vi: "639 Hz Kết Nối", en: "639 Hz Connection" }, short_benefit: { vi: "Hàn gắn mối quan hệ", en: "Heals relationships" }, long_benefits: { en: ["Enhances communication, understanding, and tolerance.", "Helps in healing and reconnecting relationships.", "Promotes harmony within family and social circles."], vi: ["Cải thiện giao tiếp, sự thấu hiểu và lòng bao dung.", "Giúp hàn gắn và kết nối lại các mối quan hệ.", "Tạo ra sự hòa hợp trong gia đình và các mối quan hệ xã hội."] }, synth_hint: { envelope: { attack:0.2, decay:1.1, sustain:0.6, release:1.4} } },
    { freq: 741, name: { vi: "741 Hz Thức Tỉnh", en: "741 Hz Awakening" }, short_benefit: { vi: "Đánh thức trực giác", en: "Awakens intuition" }, long_benefits: { en: ["Cleanses the body from toxins and electromagnetic radiation.", "Promotes self-expression and awakens intuition.", "Leads to a healthier, simpler life by solving problems."], vi: ["Thanh lọc cơ thể khỏi độc tố và bức xạ điện từ.", "Thúc đẩy sự thể hiện bản thân và đánh thức trực giác.", "Dẫn đến một cuộc sống lành mạnh, đơn giản hơn bằng cách giải quyết vấn đề."] }, synth_hint: { envelope: { attack:0.12, decay:0.9, sustain:0.5, release:1.2} } },
    { freq: 852, name: { vi: "852 Hz Tâm Linh", en: "852 Hz Spiritual" }, short_benefit: { vi: "Trở về trật tự tâm linh", en: "Returns to spiritual order" }, long_benefits: { en: ["Awakens intuition and helps you return to spiritual order.", "Raises cellular energy and awareness.", "Connects you to your higher self and universal consciousness."], vi: ["Đánh thức trực giác và giúp bạn trở về với trật tự tâm linh.", "Nâng cao năng lượng tế bào và nhận thức.", "Kết nối bạn với bản thể cao hơn và ý thức vũ trụ."] }, synth_hint: { envelope: { attack:0.15, decay:1.0, sustain:0.5, release:1.2} } },
    { freq: 963, name: { vi: "963 Hz Nguồn Cội", en: "963 Hz Source" }, short_benefit: { vi: "Kết nối năng lượng vũ trụ", en: "Connects to universal energy" }, long_benefits: { en: ["Activates the pineal gland, connecting you to the source.", "Known as the 'frequency of the gods', it awakens the crown chakra.", "Helps you experience oneness and universal energy."], vi: ["Kích hoạt tuyến tùng, kết nối bạn với cội nguồn.", "Được gọi là 'tần số của các vị thần', đánh thức luân xa vương miện.", "Giúp bạn trải nghiệm sự hợp nhất và năng lượng vũ trụ."] }, synth_hint: { envelope: { attack:0.2, decay:1.2, sustain:0.5, release:1.6} } },
];

export const binauralBeats: BinauralBeat[] = [
    { delta: 3, baseFreq: 111, name: { vi: "Sóng Delta", en: "Delta Waves" }, short_benefit: { vi: "Giấc ngủ sâu", en: "Deep sleep" }, long_benefits: { en: ["Promotes deep, restorative sleep and pain relief.", "Essential for dreamless sleep and immune system health.", "Helps access the unconscious mind and deep relaxation."], vi: ["Thúc đẩy giấc ngủ sâu, phục hồi và giảm đau.", "Cần thiết cho giấc ngủ không mơ và sức khỏe hệ miễn dịch.", "Giúp tiếp cận tiềm thức và thư giãn sâu."] }, synth_hint: { left_freq_hz: 111, right_freq_hz: 114, safe_lowpass_hz: 8000 } },
    { delta: 6, baseFreq: 120, name: { vi: "Sóng Theta", en: "Theta Waves" }, short_benefit: { vi: "Thiền định & sáng tạo", en: "Meditation & creativity" }, long_benefits: { en: ["Enhances creativity, meditation, and deep relaxation.", "Improves memory and increases intuitive insights.", "Ideal for REM sleep, learning, and stress reduction."], vi: ["Tăng cường sự sáng tạo, thiền định và thư giãn sâu.", "Cải thiện trí nhớ và tăng cường trực giác.", "Lý tưởng cho giấc ngủ REM, học tập và giảm căng thẳng."] }, synth_hint: { left_freq_hz: 120, right_freq_hz: 126, safe_lowpass_hz: 9000 } },
    { delta: 10, baseFreq: 180, name: { vi: "Sóng Alpha", en: "Alpha Waves" }, short_benefit: { vi: "Thư thái, tích cực", en: "Relaxed positivity" }, long_benefits: { en: ["Encourages a state of calm, relaxed alertness.", "Reduces stress and anxiety, promoting positivity.", "The gateway to meditation and a bridge to the subconscious."], vi: ["Khuyến khích trạng thái tỉnh táo, thư thái và bình tĩnh.", "Giảm căng thẳng và lo âu, thúc đẩy sự tích cực.", "Là cánh cổng dẫn đến thiền định và là cầu nối với tiềm thức."] }, synth_hint: { left_freq_hz: 180, right_freq_hz: 190, safe_lowpass_hz: 10000 } },
    { delta: 20, baseFreq: 220, name: { vi: "Sóng Beta", en: "Beta Waves" }, short_benefit: { vi: "Tập trung & tỉnh táo", en: "Focus & alertness" }, long_benefits: { en: ["Increases focus, alertness, and problem-solving abilities.", "Enhances cognitive function and concentration.", "Perfect for active thinking, studying, or complex tasks."], vi: ["Tăng cường sự tập trung, tỉnh táo và khả năng giải quyết vấn đề.", "Cải thiện chức năng nhận thức và sự tập trung.", "Hoàn hảo cho việc tư duy tích cực, học tập hoặc các công việc phức tạp."] }, synth_hint: { left_freq_hz: 220, right_freq_hz: 240, safe_lowpass_hz: 11000 } },
    { delta: 40, baseFreq: 300, name: { vi: "Sóng Gamma", en: "Gamma Waves" }, short_benefit: { vi: "Học tập & trí nhớ", en: "Learning & memory" }, long_benefits: { en: ["Boosts learning, memory recall, and information processing.", "Associated with peak concentration and high-level cognition.", "Enhances perception and problem-solving skills."], vi: ["Tăng cường khả năng học tập, ghi nhớ và xử lý thông tin.", "Liên quan đến sự tập trung cao độ và nhận thức cấp cao.", "Cải thiện nhận thức và kỹ năng giải quyết vấn-đề."] }, synth_hint: { left_freq_hz: 300, right_freq_hz: 340, safe_lowpass_hz: 12000 } }
];

const originalIcons: { [key: string]: string } = {
  white_noise: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>`,
  pink_noise: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>`,
  brown_noise: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2h10a2 2 0 002-2v-1a2 2 0 012-2h1.945" /></svg>`,
  rain: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10" /></svg>`,
  ocean_waves: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" /></svg>`,
  wind: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>`,
  fire: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7C14 5 16.09 5.777 17.657 7.343A8 8 0 0117.657 18.657z" /><path stroke-linecap="round" stroke-linejoin="round" d="M9.879 16.121A3 3 0 1014.12 11.88a3 3 0 00-4.242 4.242z" /></svg>`,
  stream: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16m-7 6h7" /></svg>`,
  tuning_forks_spatial: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 19V6.5a3.5 3.5 0 117 0V19M12 19v-2" /></svg>`,
  forest: `<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21V8m-4 4l4-4 4 4m-8 8h8" /></svg>`
};

export const naturalSounds: NaturalSound[] = [
  { id: "white_noise", type: "noise", noise_type: "white", icon: originalIcons.white_noise, name: { vi: "Ồn trắng", en: "White Noise" } },
  { id: "pink_noise", type: "noise", noise_type: "pink", icon: originalIcons.pink_noise, name: { vi: "Ồn hồng", en: "Pink Noise" } },
  { id: "brown_noise", type: "noise", noise_type: "brown", icon: originalIcons.brown_noise, name: { vi: "Ồn nâu", en: "Brown Noise" } },
  { id: "rain", type: "filtered_noise", noise_type: "pink", filter_freq: 1200, icon: originalIcons.rain, name: { vi: "Mưa", en: "Rain" } },
  { id: "ocean_waves", type: "lfo_noise", noise_type: "pink", lfo_freq: "8n", icon: originalIcons.ocean_waves, name: { vi: "Sóng biển", en: "Ocean Waves" } },
  { id: "wind", type: "lfo_noise", noise_type: "brown", lfo_freq: "4n", icon: originalIcons.wind, name: { vi: "Gió", en: "Wind" } },
  { id: "fire", type: "fire", icon: originalIcons.fire, name: { vi: "Lửa", en: "Fire" } },
  { id: "stream", type: "filtered_noise", noise_type: "white", filter_freq: 2000, icon: originalIcons.stream, name: { vi: "Suối", en: "Stream" } },
  { id: "tuning_forks_spatial", type: "tuning_forks_spatial", icon: originalIcons.tuning_forks_spatial, name: { vi: "Âm Thoa 3D", en: "Spatial Forks" } },
  { id: "forest", type: "forest", icon: originalIcons.forest, name: { vi: "Rừng rậm", en: "Forest", zh: "森林", ja: "森林", ko: "숲", fr: "Forêt", de: "Wald", es: "Bosque" } },
  { id: "gentle_stream", type: "filtered_noise", noise_type: "pink", filter_freq: 1600, icon: originalIcons.stream, name: { vi: "Suối nhẹ", en: "Gentle Stream", zh: "潺潺溪流", ja: "穏やかな小川", ko: "부드러운 시냇물", fr: "Doux Ruisseau", de: "Sanfter Bach", es: "Arroyo Suave" } },
];
